package com.megvii.qa.model;

public class TaskLogWithBLOBs extends TaskLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QA_TEST_QRTZ_TRIGGER_LOG.trigger_msg
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    private String triggerMsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QA_TEST_QRTZ_TRIGGER_LOG.handle_msg
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    private String handleMsg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QA_TEST_QRTZ_TRIGGER_LOG.trigger_msg
     *
     * @return the value of QA_TEST_QRTZ_TRIGGER_LOG.trigger_msg
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    public String getTriggerMsg() {
        return triggerMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QA_TEST_QRTZ_TRIGGER_LOG.trigger_msg
     *
     * @param triggerMsg the value for QA_TEST_QRTZ_TRIGGER_LOG.trigger_msg
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    public void setTriggerMsg(String triggerMsg) {
        this.triggerMsg = triggerMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QA_TEST_QRTZ_TRIGGER_LOG.handle_msg
     *
     * @return the value of QA_TEST_QRTZ_TRIGGER_LOG.handle_msg
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    public String getHandleMsg() {
        return handleMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QA_TEST_QRTZ_TRIGGER_LOG.handle_msg
     *
     * @param handleMsg the value for QA_TEST_QRTZ_TRIGGER_LOG.handle_msg
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    public void setHandleMsg(String handleMsg) {
        this.handleMsg = handleMsg;
    }
}