package com.megvii.qa.model;

import java.util.Date;

public class TaskLogGlue {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QA_TEST_QRTZ_TRIGGER_LOGGLUE.id
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QA_TEST_QRTZ_TRIGGER_LOGGLUE.job_id
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    private Integer jobId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QA_TEST_QRTZ_TRIGGER_LOGGLUE.glue_type
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    private String glueType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QA_TEST_QRTZ_TRIGGER_LOGGLUE.glue_remark
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    private String glueRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QA_TEST_QRTZ_TRIGGER_LOGGLUE.add_time
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QA_TEST_QRTZ_TRIGGER_LOGGLUE.update_time
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QA_TEST_QRTZ_TRIGGER_LOGGLUE.glue_source
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    private String glueSource;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QA_TEST_QRTZ_TRIGGER_LOGGLUE.id
     *
     * @return the value of QA_TEST_QRTZ_TRIGGER_LOGGLUE.id
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QA_TEST_QRTZ_TRIGGER_LOGGLUE.id
     *
     * @param id the value for QA_TEST_QRTZ_TRIGGER_LOGGLUE.id
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QA_TEST_QRTZ_TRIGGER_LOGGLUE.job_id
     *
     * @return the value of QA_TEST_QRTZ_TRIGGER_LOGGLUE.job_id
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    public Integer getJobId() {
        return jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QA_TEST_QRTZ_TRIGGER_LOGGLUE.job_id
     *
     * @param jobId the value for QA_TEST_QRTZ_TRIGGER_LOGGLUE.job_id
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    public void setJobId(Integer jobId) {
        this.jobId = jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QA_TEST_QRTZ_TRIGGER_LOGGLUE.glue_type
     *
     * @return the value of QA_TEST_QRTZ_TRIGGER_LOGGLUE.glue_type
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    public String getGlueType() {
        return glueType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QA_TEST_QRTZ_TRIGGER_LOGGLUE.glue_type
     *
     * @param glueType the value for QA_TEST_QRTZ_TRIGGER_LOGGLUE.glue_type
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    public void setGlueType(String glueType) {
        this.glueType = glueType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QA_TEST_QRTZ_TRIGGER_LOGGLUE.glue_remark
     *
     * @return the value of QA_TEST_QRTZ_TRIGGER_LOGGLUE.glue_remark
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    public String getGlueRemark() {
        return glueRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QA_TEST_QRTZ_TRIGGER_LOGGLUE.glue_remark
     *
     * @param glueRemark the value for QA_TEST_QRTZ_TRIGGER_LOGGLUE.glue_remark
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    public void setGlueRemark(String glueRemark) {
        this.glueRemark = glueRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QA_TEST_QRTZ_TRIGGER_LOGGLUE.add_time
     *
     * @return the value of QA_TEST_QRTZ_TRIGGER_LOGGLUE.add_time
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QA_TEST_QRTZ_TRIGGER_LOGGLUE.add_time
     *
     * @param addTime the value for QA_TEST_QRTZ_TRIGGER_LOGGLUE.add_time
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QA_TEST_QRTZ_TRIGGER_LOGGLUE.update_time
     *
     * @return the value of QA_TEST_QRTZ_TRIGGER_LOGGLUE.update_time
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QA_TEST_QRTZ_TRIGGER_LOGGLUE.update_time
     *
     * @param updateTime the value for QA_TEST_QRTZ_TRIGGER_LOGGLUE.update_time
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QA_TEST_QRTZ_TRIGGER_LOGGLUE.glue_source
     *
     * @return the value of QA_TEST_QRTZ_TRIGGER_LOGGLUE.glue_source
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    public String getGlueSource() {
        return glueSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QA_TEST_QRTZ_TRIGGER_LOGGLUE.glue_source
     *
     * @param glueSource the value for QA_TEST_QRTZ_TRIGGER_LOGGLUE.glue_source
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    public void setGlueSource(String glueSource) {
        this.glueSource = glueSource;
    }
}