package com.megvii.qa.model;

import java.util.Date;

public class TaskLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QA_TEST_QRTZ_TRIGGER_LOG.id
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QA_TEST_QRTZ_TRIGGER_LOG.job_id
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    private Integer jobId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QA_TEST_QRTZ_TRIGGER_LOG.executor_param
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    private String executorParam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QA_TEST_QRTZ_TRIGGER_LOG.executor_fail_retry_count
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    private Integer executorFailRetryCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QA_TEST_QRTZ_TRIGGER_LOG.trigger_time
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    private Date triggerTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QA_TEST_QRTZ_TRIGGER_LOG.trigger_code
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    private Integer triggerCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QA_TEST_QRTZ_TRIGGER_LOG.handle_time
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    private Date handleTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QA_TEST_QRTZ_TRIGGER_LOG.handle_code
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    private Integer handleCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QA_TEST_QRTZ_TRIGGER_LOG.alarm_status
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    private Byte alarmStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QA_TEST_QRTZ_TRIGGER_LOG.id
     *
     * @return the value of QA_TEST_QRTZ_TRIGGER_LOG.id
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QA_TEST_QRTZ_TRIGGER_LOG.id
     *
     * @param id the value for QA_TEST_QRTZ_TRIGGER_LOG.id
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QA_TEST_QRTZ_TRIGGER_LOG.job_id
     *
     * @return the value of QA_TEST_QRTZ_TRIGGER_LOG.job_id
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    public Integer getJobId() {
        return jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QA_TEST_QRTZ_TRIGGER_LOG.job_id
     *
     * @param jobId the value for QA_TEST_QRTZ_TRIGGER_LOG.job_id
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    public void setJobId(Integer jobId) {
        this.jobId = jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QA_TEST_QRTZ_TRIGGER_LOG.executor_param
     *
     * @return the value of QA_TEST_QRTZ_TRIGGER_LOG.executor_param
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    public String getExecutorParam() {
        return executorParam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QA_TEST_QRTZ_TRIGGER_LOG.executor_param
     *
     * @param executorParam the value for QA_TEST_QRTZ_TRIGGER_LOG.executor_param
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    public void setExecutorParam(String executorParam) {
        this.executorParam = executorParam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QA_TEST_QRTZ_TRIGGER_LOG.executor_fail_retry_count
     *
     * @return the value of QA_TEST_QRTZ_TRIGGER_LOG.executor_fail_retry_count
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    public Integer getExecutorFailRetryCount() {
        return executorFailRetryCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QA_TEST_QRTZ_TRIGGER_LOG.executor_fail_retry_count
     *
     * @param executorFailRetryCount the value for QA_TEST_QRTZ_TRIGGER_LOG.executor_fail_retry_count
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    public void setExecutorFailRetryCount(Integer executorFailRetryCount) {
        this.executorFailRetryCount = executorFailRetryCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QA_TEST_QRTZ_TRIGGER_LOG.trigger_time
     *
     * @return the value of QA_TEST_QRTZ_TRIGGER_LOG.trigger_time
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    public Date getTriggerTime() {
        return triggerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QA_TEST_QRTZ_TRIGGER_LOG.trigger_time
     *
     * @param triggerTime the value for QA_TEST_QRTZ_TRIGGER_LOG.trigger_time
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    public void setTriggerTime(Date triggerTime) {
        this.triggerTime = triggerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QA_TEST_QRTZ_TRIGGER_LOG.trigger_code
     *
     * @return the value of QA_TEST_QRTZ_TRIGGER_LOG.trigger_code
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    public Integer getTriggerCode() {
        return triggerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QA_TEST_QRTZ_TRIGGER_LOG.trigger_code
     *
     * @param triggerCode the value for QA_TEST_QRTZ_TRIGGER_LOG.trigger_code
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    public void setTriggerCode(Integer triggerCode) {
        this.triggerCode = triggerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QA_TEST_QRTZ_TRIGGER_LOG.handle_time
     *
     * @return the value of QA_TEST_QRTZ_TRIGGER_LOG.handle_time
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    public Date getHandleTime() {
        return handleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QA_TEST_QRTZ_TRIGGER_LOG.handle_time
     *
     * @param handleTime the value for QA_TEST_QRTZ_TRIGGER_LOG.handle_time
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    public void setHandleTime(Date handleTime) {
        this.handleTime = handleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QA_TEST_QRTZ_TRIGGER_LOG.handle_code
     *
     * @return the value of QA_TEST_QRTZ_TRIGGER_LOG.handle_code
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    public Integer getHandleCode() {
        return handleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QA_TEST_QRTZ_TRIGGER_LOG.handle_code
     *
     * @param handleCode the value for QA_TEST_QRTZ_TRIGGER_LOG.handle_code
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    public void setHandleCode(Integer handleCode) {
        this.handleCode = handleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QA_TEST_QRTZ_TRIGGER_LOG.alarm_status
     *
     * @return the value of QA_TEST_QRTZ_TRIGGER_LOG.alarm_status
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    public Byte getAlarmStatus() {
        return alarmStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QA_TEST_QRTZ_TRIGGER_LOG.alarm_status
     *
     * @param alarmStatus the value for QA_TEST_QRTZ_TRIGGER_LOG.alarm_status
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    public void setAlarmStatus(Byte alarmStatus) {
        this.alarmStatus = alarmStatus;
    }
}