package com.megvii.qa.model;

import java.util.Date;

public class TaskRegistry {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QA_TEST_QRTZ_TRIGGER_REGISTRY.id
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QA_TEST_QRTZ_TRIGGER_REGISTRY.registry_group
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    private String registryGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QA_TEST_QRTZ_TRIGGER_REGISTRY.registry_key
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    private String registryKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QA_TEST_QRTZ_TRIGGER_REGISTRY.registry_value
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    private String registryValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QA_TEST_QRTZ_TRIGGER_REGISTRY.update_time
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QA_TEST_QRTZ_TRIGGER_REGISTRY.id
     *
     * @return the value of QA_TEST_QRTZ_TRIGGER_REGISTRY.id
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QA_TEST_QRTZ_TRIGGER_REGISTRY.id
     *
     * @param id the value for QA_TEST_QRTZ_TRIGGER_REGISTRY.id
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QA_TEST_QRTZ_TRIGGER_REGISTRY.registry_group
     *
     * @return the value of QA_TEST_QRTZ_TRIGGER_REGISTRY.registry_group
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    public String getRegistryGroup() {
        return registryGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QA_TEST_QRTZ_TRIGGER_REGISTRY.registry_group
     *
     * @param registryGroup the value for QA_TEST_QRTZ_TRIGGER_REGISTRY.registry_group
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    public void setRegistryGroup(String registryGroup) {
        this.registryGroup = registryGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QA_TEST_QRTZ_TRIGGER_REGISTRY.registry_key
     *
     * @return the value of QA_TEST_QRTZ_TRIGGER_REGISTRY.registry_key
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    public String getRegistryKey() {
        return registryKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QA_TEST_QRTZ_TRIGGER_REGISTRY.registry_key
     *
     * @param registryKey the value for QA_TEST_QRTZ_TRIGGER_REGISTRY.registry_key
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    public void setRegistryKey(String registryKey) {
        this.registryKey = registryKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QA_TEST_QRTZ_TRIGGER_REGISTRY.registry_value
     *
     * @return the value of QA_TEST_QRTZ_TRIGGER_REGISTRY.registry_value
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    public String getRegistryValue() {
        return registryValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QA_TEST_QRTZ_TRIGGER_REGISTRY.registry_value
     *
     * @param registryValue the value for QA_TEST_QRTZ_TRIGGER_REGISTRY.registry_value
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    public void setRegistryValue(String registryValue) {
        this.registryValue = registryValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QA_TEST_QRTZ_TRIGGER_REGISTRY.update_time
     *
     * @return the value of QA_TEST_QRTZ_TRIGGER_REGISTRY.update_time
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QA_TEST_QRTZ_TRIGGER_REGISTRY.update_time
     *
     * @param updateTime the value for QA_TEST_QRTZ_TRIGGER_REGISTRY.update_time
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}