package com.megvii.qa.dao;

import com.megvii.qa.model.TaskLogGlue;

public interface TaskLogGlueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QA_TEST_QRTZ_TRIGGER_LOGGLUE
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QA_TEST_QRTZ_TRIGGER_LOGGLUE
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    int insert(TaskLogGlue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QA_TEST_QRTZ_TRIGGER_LOGGLUE
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    int insertSelective(TaskLogGlue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QA_TEST_QRTZ_TRIGGER_LOGGLUE
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    TaskLogGlue selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QA_TEST_QRTZ_TRIGGER_LOGGLUE
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    int updateByPrimaryKeySelective(TaskLogGlue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QA_TEST_QRTZ_TRIGGER_LOGGLUE
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(TaskLogGlue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QA_TEST_QRTZ_TRIGGER_LOGGLUE
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    int updateByPrimaryKey(TaskLogGlue record);
}