package com.megvii.qa.dao;

import com.megvii.qa.model.TaskLog;
import com.megvii.qa.model.TaskLogWithBLOBs;

public interface TaskLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QA_TEST_QRTZ_TRIGGER_LOG
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QA_TEST_QRTZ_TRIGGER_LOG
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    int insert(TaskLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QA_TEST_QRTZ_TRIGGER_LOG
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    int insertSelective(TaskLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QA_TEST_QRTZ_TRIGGER_LOG
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    TaskLogWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QA_TEST_QRTZ_TRIGGER_LOG
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    int updateByPrimaryKeySelective(TaskLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QA_TEST_QRTZ_TRIGGER_LOG
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(TaskLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QA_TEST_QRTZ_TRIGGER_LOG
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    int updateByPrimaryKey(TaskLog record);
}