package com.megvii.qa.dao;

import com.megvii.qa.model.TaskRegistry;

public interface TaskRegistryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QA_TEST_QRTZ_TRIGGER_REGISTRY
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QA_TEST_QRTZ_TRIGGER_REGISTRY
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    int insert(TaskRegistry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QA_TEST_QRTZ_TRIGGER_REGISTRY
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    int insertSelective(TaskRegistry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QA_TEST_QRTZ_TRIGGER_REGISTRY
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    TaskRegistry selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QA_TEST_QRTZ_TRIGGER_REGISTRY
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    int updateByPrimaryKeySelective(TaskRegistry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QA_TEST_QRTZ_TRIGGER_REGISTRY
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    int updateByPrimaryKey(TaskRegistry record);
}