package com.megvii.qa.dao;

import com.megvii.qa.model.TaskInfo;

public interface TaskInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QA_TEST_ORTZ_TRIGGER_INFO
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QA_TEST_ORTZ_TRIGGER_INFO
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    int insert(TaskInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QA_TEST_ORTZ_TRIGGER_INFO
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    int insertSelective(TaskInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QA_TEST_ORTZ_TRIGGER_INFO
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    TaskInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QA_TEST_ORTZ_TRIGGER_INFO
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    int updateByPrimaryKeySelective(TaskInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QA_TEST_ORTZ_TRIGGER_INFO
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(TaskInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QA_TEST_ORTZ_TRIGGER_INFO
     *
     * @mbggenerated Thu Jan 24 14:32:36 CST 2019
     */
    int updateByPrimaryKey(TaskInfo record);
}